eureka: 
  client: 
    fetchRegistry: false
    registerWithEureka: false
  server: 
    waitTimeInMsWhenSyncEmpty: 5
    wait-time-in-ms-when-sync-empty: 0

server: 
  port: 8761
  
spring: 
  application: 
    name: eureka  